<?php

Yii::import('zii.widgets.CMenu');

class Menu extends CMenu {
	/**
	 * Checks whether a menu item is active.
	 * This is done by checking if the currently requested URL is generated by the 'url' option
	 * of the menu item. Note that the GET parameters not specified in the 'url' option will be ignored.
	 * @param array $item the menu item to be checked
	 * @param string $route the route of the current request
	 * @return boolean whether the menu item is active
	 */
	protected function isItemActive($item, $route) {
		if (isset($item['url']) && is_array($item['url']) && isset($item['url'][0])) {
			$itemRoute = $item['url'][0];
			$controller = Yii::app()->controller;
			if ($itemRoute === '') {
				$itemRoute = $controller->getId() . '/' . $controller->getAction()->getId();
			} else {
				if (strpos($itemRoute, '/') === false) {
					$itemRoute = $controller->getId() . '/' . $itemRoute;
				}
			}
			if ($itemRoute[0] !== '/' && ($module = $controller->getModule()) !== null) {
				$itemRoute = $module->getId() . '/' . $itemRoute;
			}

			if (!strcasecmp(trim($itemRoute, '/'), $route)) {
				unset($item['url']['#']);
				if (count($item['url']) > 1) {
					foreach (array_splice($item['url'], 1) as $name => $value) {
						if (!isset($_GET[$name]) || $_GET[$name] != $value) {
							return false;
						}
					}
				}
				return true;
			}
		}

		return false;
	}
}